from time import sleep
from colorama import Fore, Back, Style

print(Fore.WHITE)
print("                                                     ")
print("   __        __   _                                  ") ; sleep(0.2)
print("   \ \      / /__| | ___ ___  _ __ ___   ___         ") ; sleep(0.2)
print("    \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \        ") ; sleep(0.2)
print("     \ V  V /  __/ | (_| (_) | | | | | |  __/        ") ; sleep(0.2)
print("      \_/\_/ \___|_|\___\___/|_| |_| |_|\___|        ") ; sleep(0.2)
print("                                                     ") ; sleep(0.2)
print("                                                     ") ; sleep(0.12)
print("   -----------------------------------------------   ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print("  _ Loading, please wait...                          ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print("  [	2.20160524] sd 0:0:0:0:0ddbu22 [Ded]	Assuming drive cache: write through") ; sleep(0.12)
print("  Valid path for Logical Volume.                     ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" /home/user1/My\ World/Presentation.zip: clean, 1704684/10121909 Files, 3813438/7532544 blocks") ; sleep(0.12)
print(" Started:		Attempting to mount PAOS fuse mount.") ; sleep(0.12)
print(" See ""Systemctl status: ""runPAOS\\fuse.mount"" for debug details.") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" [  0.000000]  init_memory_mapping: [mem 0x00100000-0xdefa4fff]") ; sleep(0.12)
print(" [  1.169734]  [mem 0x00100000-0x001fffff]") ; sleep(0.12)
print(" [  0.310006]  NetLabel: protocols = UNLABLED DEDsec0v4") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" Freeing init memory: 18780K (ffff880035b42000 - fffff880036d99000)") ; sleep(0.12)
print(" PCI-DMA: Using software bounce buffering for IO (CHDed)                                                    ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" status: OK EXT4-fs  (sda1): orphan cleanup on readonly fs") ; sleep(0.12)
print(" status: OK EXT4-fs  (sda1): recovery complete") ; sleep(0.12)
print(" status: OK EXT4-fs  (sda1): mounted filesystem with orderd data mode.") ; sleep(0.12)
print(" status: OK found BLUME MP-table mapped at [mem 0x10121989-0x000f9bff]") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" Scanning 1 area(s) for low memory corruption for write") ; sleep(0.12)
print(" Monitoring of Blume mirrors... ng dmeventd or cloud polling.") ; sleep(0.12)
print(" init_memory_mapping: [mem 0x0000000-0x000ACK]") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" Mounted device PAOSware: PAOS00 login:            ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print("   -----------------------------------------------   ") ; sleep(0.12)
print("                                                     ") ; sleep(0.12)
print(" Attempting File Repair - 01%                        ") ; sleep(0.16)
print(" Attempting File Repair - 02%                        ") ; sleep(0.16)
print(" Attempting File Repair - 03%                        ") ; sleep(0.16)
print(" Attempting File Repair - 04%                        ") ; sleep(0.16)
print(" Attempting File Repair - 05%                        ") ; sleep(0.16)
print(" Attempting File Repair - 06%                        ") ; sleep(1.2)
print(" Attempting File Repair - 07%                        ") ; sleep(0.17)
print(" Attempting File Repair - 08%                        ") ; sleep(0.16)
print(" Attempting File Repair - 09%                        ") ; sleep(0.16)
print(" Attempting File Repair - 10%                        ") ; sleep(0.16)
print(" Attempting File Repair - 11%                        ") ; sleep(0.16)
print(" Attempting File Repair - 12%                        ") ; sleep(0.16)
print(" Attempting File Repair - 13%                        ") ; sleep(0.16)
print(" Attempting File Repair - 14%                        ") ; sleep(0.16)
print(" Attempting File Repair - 15%                        ") ; sleep(0.16)
print(" Attempting File Repair - 16%                        ") ; sleep(0.16)
print(" Attempting File Repair - 17%                        ") ; sleep(0.16)
print(" Attempting File Repair - 18%                        ") ; sleep(0.16)
print(" Attempting File Repair - 19%                        ") ; sleep(0.16)
print(" Attempting File Repair - 20%                        ") ; sleep(0.16)
print(" Attempting File Repair - 21%                        ") ; sleep(0.16)
print(" Attempting File Repair - 22%                        ") ; sleep(0.16)
print(" Attempting File Repair - 23%                        ") ; sleep(0.16)
print(" Attempting File Repair - 24%                        ") ; sleep(0.16)
print(" Attempting File Repair - 25%                        ") ; sleep(0.16)
print(" Attempting File Repair - 26%                        ") ; sleep(0.16)
print(" Attempting File Repair - 27%                        ") ; sleep(0.16)
print(" Attempting File Repair - 28%                        ") ; sleep(0.16)
print(" Attempting File Repair - 29%                        ") ; sleep(0.16)
print(" Attempting File Repair - 30%                        ") ; sleep(0.16)
print(" Attempting File Repair - 31%                        ") ; sleep(0.16)
print(" Attempting File Repair - 32%                        ") ; sleep(0.16)
print(" Attempting File Repair - 33%                        ") ; sleep(0.16)
print(" Attempting File Repair - 34%                        ") ; sleep(0.16)
print(" Attempting File Repair - 35%                        ") ; sleep(0.16)
print(" Attempting File Repair - 36%                        ") ; sleep(0.16)
print(" Attempting File Repair - 37%                        ") ; sleep(0.16)
print(" Attempting File Repair - 38%                        ") ; sleep(0.16)
print(" Attempting File Repair - 39%                        ") ; sleep(0.16)
print(" Attempting File Repair - 40%                        ") ; sleep(0.16)
print(" Attempting File Repair - 41%                        ") ; sleep(0.16)
print(" Attempting File Repair - 42%                        ") ; sleep(0.16)
print(" Attempting File Repair - 43%                        ") ; sleep(0.16)
print(" Attempting File Repair - 44%                        ") ; sleep(0.16)
print(" Attempting File Repair - 45%                        ") ; sleep(0.16)
print(" Attempting File Repair - 46%                        ") ; sleep(0.16)
print(" Attempting File Repair - 47%                        ") ; sleep(0.16)
print(" Attempting File Repair - 48%                        ") ; sleep(0.16)
print(" Attempting File Repair - 49%                        ") ; sleep(0.16)
print(" Attempting File Repair - 50%                        ") ; sleep(0.5)
print(" Attempting File Repair - 51%                        ") ; sleep(0.7)
print(" Attempting File Repair - 52%                        ") ; sleep(0.9)
print(" Attempting File Repair - 53%                        ") ; sleep(6)
print(" Attempting File Repair - 54%                        ") ; sleep(0.16)
print(" Attempting File Repair - 55%                        ") ; sleep(0.16)
print(" Attempting File Repair - 56%                        ") ; sleep(0.16)
print(" Attempting File Repair - 57%                        ") ; sleep(0.16)
print(" Attempting File Repair - 58%                        ") ; sleep(0.16)
print(" Attempting File Repair - 59%                        ") ; sleep(3)
print(" Attempting File Repair - 60%                        ") ; sleep(0.16)
print(" Attempting File Repair - 61%                        ") ; sleep(0.16)
print(" Attempting File Repair - 62%                        ") ; sleep(0.16)
print(" Attempting File Repair - 63%                        ") ; sleep(0.16)
print(" Attempting File Repair - 64%                        ") ; sleep(0.16)
print(" Attempting File Repair - 65%                        ") ; sleep(0.16)
print(" Attempting File Repair - 66%                        ") ; sleep(0.16)
print(" Attempting File Repair - 67%                        ") ; sleep(0.16)
print(" Attempting File Repair - 68%                        ") ; sleep(0.16)
print(" Attempting File Repair - 69%                        ") ; sleep(0.16)
print(" Attempting File Repair - 70%                        ") ; sleep(0.16)
print(" Attempting File Repair - 71%                        ") ; sleep(2)
print(" Attempting File Repair - 72%                        ") ; sleep(0.16)
print(" Attempting File Repair - 73%                        ") ; sleep(0.16)
print(" Attempting File Repair - 74%                        ") ; sleep(0.16)
print(" Attempting File Repair - 75%                        ") ; sleep(0.16)
print(" Attempting File Repair - 76%                        ") ; sleep(0.16)
print(" Attempting File Repair - 77%                        ") ; sleep(0.16)
print(" Attempting File Repair - 78%                        ") ; sleep(0.16)
print(" Attempting File Repair - 79%                        ") ; sleep(0.16)
print(" Attempting File Repair - 80%                        ") ; sleep(2)
print(" Attempting File Repair - 81%                        ") ; sleep(0.16)
print(" Attempting File Repair - 82%                        ") ; sleep(0.16)
print(" Attempting File Repair - 83%                        ") ; sleep(0.16)
print(" Attempting File Repair - 84%                        ") ; sleep(0.16)
print(" Attempting File Repair - 85%                        ") ; sleep(0.16)
print(" Attempting File Repair - 86%                        ") ; sleep(0.16)
print(" Attempting File Repair - 87%                        ") ; sleep(0.16)
print(" Attempting File Repair - 88%                        ") ; sleep(0.16)
print(" Attempting File Repair - 89%                        ") ; sleep(0.16)
print(" Attempting File Repair - 90%                        ") ; sleep(0.16)
print(" Attempting File Repair - 91%                        ") ; sleep(1)
print(" Attempting File Repair - 92%                        ") ; sleep(0.16)
print(" Attempting File Repair - 93%                        ") ; sleep(0.16)
print(" Attempting File Repair - 94%                        ") ; sleep(0.16)
print(" Attempting File Repair - 95%                        ") ; sleep(0.16)
print(" Attempting File Repair - 96%                        ") ; sleep(0.16)
print(" Attempting File Repair - 97%                        ") ; sleep(0.16)
print(" Attempting File Repair - 98%                        ") ; sleep(0.16)
print(" Attempting File Repair - 99%                        ") ; sleep(6.73)
print(" Attempting File Repair - 100%                       ") ; sleep(0.16)
print(" Attempting File Repair - FINISHED!                  ") ; sleep(0.7)
print(" File Repair - FAILED!!                              ") ; sleep(1.0)
print("                                                     ")
print("                                                     ")
print("                                                     ")
retry = input("Do you want to try the script again?")
if retry == ("Y"):
	print ("OK - RETRYING")
	print (" ")
	print("  _ Loading, please wait...                          ") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print("  [	2.20160524] sd 0:0:0:0:0ddbu22 [Ded]	Assuming drive cache: write through") ; sleep(0.12)
	print("  Valid path for Logical Volume.                     ") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" /home/user/My\ World/Presentation.zip: clean, 1704684/10121909 Files, 3813438/7532544 blocks") ; sleep(0.12)
	print(" Started:		Attempting to mount PAOS fuse mount.") ; sleep(0.12)
	print(" See ""Systemctl status: ""runPAOS\\fuse.mount"" for debug details.") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" [  0.000000]  init_memory_mapping: [mem 0x00100000-0xdefa4fff]") ; sleep(0.12)
	print(" [  1.169734]  [mem 0x00100000-0x001fffff]") ; sleep(0.12)
	print(" [  0.310006]  NetLabel: protocols = UNLABLED DEDsec0v4") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" Freeing init memory: 18780K (ffff880035b42000 - fffff880036d99000)") ; sleep(0.12)
	print(" PCI-DMA: Using software bounce buffering for IO (CHDed)                                                    ") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" status: OK EXT4-fs  (sda1): orphan cleanup on readonly fs") ; sleep(0.12)
	print(" status: OK EXT4-fs  (sda1): recovery complete") ; sleep(0.12)
	print(" status: OK EXT4-fs  (sda1): mounted filesystem with orderd data mode.") ; sleep(0.12)
	print(" status: OK found BLUME MP-table mapped at [mem 0x10121989-0x000f9bff]") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" Scanning 1 area(s) for low memory corruption for write") ; sleep(0.12)
	print(" Monitoring of Blume mirrors... ng dmeventd or cloud polling.") ; sleep(0.12)
	print(" init_memory_mapping: [mem 0x0000000-0x000ACK]") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" Mounted device PAOSware: PAOS00 login:            ") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print("   -----------------------------------------------   ") ; sleep(0.12)
	print("                                                     ") ; sleep(0.12)
	print(" Attempting File Repair - 01%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 02%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 03%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 04%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 05%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 06%                        ") ; sleep(1.2)
	print(" Attempting File Repair - 07%                        ") ; sleep(0.17)
	print(" Attempting File Repair - 08%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 09%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 10%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 11%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 12%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 13%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 14%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 15%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 16%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 17%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 18%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 19%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 20%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 21%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 22%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 23%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 24%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 25%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 26%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 27%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 28%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 29%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 30%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 31%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 32%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 33%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 34%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 35%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 36%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 37%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 38%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 39%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 40%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 41%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 42%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 43%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 44%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 45%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 46%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 47%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 48%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 49%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 50%                        ") ; sleep(0.5)
	print(" Attempting File Repair - 51%                        ") ; sleep(0.7)
	print(" Attempting File Repair - 52%                        ") ; sleep(0.9)
	print(" Attempting File Repair - 53%                        ") ; sleep(6)
	print(" Attempting File Repair - 54%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 55%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 56%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 57%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 58%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 59%                        ") ; sleep(3)
	print(" Attempting File Repair - 60%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 61%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 62%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 63%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 64%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 65%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 66%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 67%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 68%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 69%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 70%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 71%                        ") ; sleep(2)
	print(" Attempting File Repair - 72%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 73%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 74%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 75%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 76%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 77%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 78%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 79%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 80%                        ") ; sleep(2)
	print(" Attempting File Repair - 81%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 82%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 83%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 84%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 85%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 86%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 87%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 88%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 89%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 90%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 91%                        ") ; sleep(1)
	print(" Attempting File Repair - 92%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 93%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 94%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 95%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 96%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 97%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 98%                        ") ; sleep(0.16)
	print(" Attempting File Repair - 99%                        ") ; sleep(6.73)
	print(" Attempting File Repair - 100%                       ") ; sleep(0.16)
	print(" Attempting File Repair - FINISHED!                  ") ; sleep(0.7)
	print(" File Repair - INCONCLUSIVE!!                        ") ; sleep(1.0)
	print(" See path '/home/user1/Desktop/Scripts/filesystem/repairattempt01' for details") ; sleep(1.0)
elif retry == ("N"):
	print ("EXITING")
